org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47.4.10,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

mod_id=jsgzpm
mod_name=JSG-ZPM
mod_version=0.1.0-phase1
mod_group_id=uk.co.atty29.jsgzpm
mod_authors=Atty29
mod_description=Zero Point Module power infrastructure and Atlantis technology addon for Just Stargate Mod.
mod_license=All Rights Reserved

default_zpm_capacity=100000000000
