"""Original circular recharger chamber and runtime mesh. No reference pixels sampled."""
from pathlib import Path
import math,struct,zlib,base64,json
from build_ancient_assets import Mesh,ROOT,ASSETS

# Coordinates are (u, v, outward) from controller centre, independent of mounting face.
def build():
    m=Mesh()
    def tube(levels,mat,inside=False):
        temp=Mesh();temp.lathe(0,0,levels,mat,n=48,cap=False)
        for pts,material in temp.faces:
            # A proper rotation maps the lathe Y axis onto chamber depth.
            pts=[(x,-z,y) for x,y,z in pts]
            m.face(list(reversed(pts)) if inside else pts,material)
    def annulus(depth,inner,outer,mat):
        temp=Mesh();temp.ring(0,0,depth,inner,outer,mat,n=48)
        for pts,material in temp.faces:
            if inner==0:pts=pts[1:]
            m.face([(x,-z,y) for x,y,z in pts],material)
    tube([(.51,1.38),(.66,1.46),(1.58,1.46),(1.80,1.38)],'dark')
    tube([(.57,.94),(1.20,.94),(1.70,.96)],'metal',True)
    annulus(.56,0,.94,'dark')
    annulus(1.80,.96,1.38,'metal')
    annulus(1.81,1.29,1.35,'dark')
    annulus(1.82,1.35,1.40,'metal')
    annulus(1.705,.94,1.04,'dark')
    # Repeated structural ribs and rectangular instrumentation around the mouth.
    def radial_box(angle,lo,hi,mat):
        temp=Mesh();temp.box(lo,hi,mat)
        c,s=math.cos(angle),math.sin(angle)
        for pts,material in temp.faces:m.face([(x*c-y*s,x*s+y*c,z) for x,y,z in pts],material)
    for i in range(48):
        a=i*math.tau/48
        radial_box(a,(1.055,-.016,1.79),(1.27,.016,1.835),'dark')
        radial_box(a,(1.39,-.011,.63),(1.475,.011,1.64),'metal')
    for i in range(12):
        a=i*math.tau/12
        radial_box(a,(1.30,-.085,1.815),(1.42,.085,1.85),'dark')
    # Central three-slot rack: modules remain upright in the chamber's local plane.
    m.box((-.73,-.32,.85),(.73,-.255,1.29),'dark')
    m.box((-.67,-.265,.91),(.67,-.24,1.23),'metal')
    for x in [-.44,0,.44]:
        temp=Mesh();temp.lathe(x,1.07,[(-.24,.135),(-.195,.135)],'metal',n=16,cap=False)
        m.faces.extend(temp.faces)
        m.ring(x,1.07,-.195,.110,.135,'metal',n=16)
    m.box((-.10,-.87,.94),(.10,-.32,1.18),'dark')
    # Compact lossless runtime mesh; avoid Java's method-size/string-size limits.
    payload=struct.pack('>i',len(m.faces))
    for pts,mat in m.faces:
        if len(pts)==3:pts=pts+[pts[-1]]
        a,b,c=pts[:3];u=[b[i]-a[i] for i in range(3)];v=[c[i]-a[i] for i in range(3)]
        n=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]]
        length=math.sqrt(sum(q*q for q in n));n=[q/length for q in n]
        payload+=struct.pack('>16f',*(q for p in pts for q in p),*n,0 if mat=='dark' else 1)
    encoded=base64.b64encode(zlib.compress(payload,9)).decode()
    java='''package uk.co.atty29.jsgzpm.client;

import java.io.ByteArrayInputStream;
import java.io.DataInputStream;
import java.io.IOException;
import java.util.Base64;
import java.util.zip.InflaterInputStream;

// Original mesh generated by tools/build_recharger_assets.py.
public final class RechargerMesh {
    private RechargerMesh() {}
    public static final float[][] FACES = decode(
'''
    java+=' +\n'.join('        "'+encoded[i:i+12000]+'"' for i in range(0,len(encoded),12000))+');\n'
    java+='''    private static float[][] decode(String data) {
        try (DataInputStream in = new DataInputStream(new InflaterInputStream(new ByteArrayInputStream(Base64.getDecoder().decode(data))))) {
            float[][] faces = new float[in.readInt()][16];
            for (float[] face : faces) for (int i=0;i<16;i++) face[i]=in.readFloat();
            return faces;
        } catch (IOException ex) { throw new ExceptionInInitializerError(ex); }
    }
}
'''
    (ROOT/'src/main/java/uk/co/atty29/jsgzpm/client/RechargerMesh.java').write_text(java)
    # Procedural soft circular mist and a transparent containment grid.
    out=ASSETS/'textures/entity';out.mkdir(parents=True,exist_ok=True)
    def chunk(tag,data):return struct.pack('!I',len(data))+tag+data+struct.pack('!I',zlib.crc32(tag+data))
    for name in ['recharger_mist','recharger_shield']:
        rows=[]
        for y in range(128):
            row=bytearray([0])
            for x in range(128):
                u,v=(x-63.5)/63.5,(y-63.5)/63.5;r=math.hypot(u,v)
                if name=='recharger_mist':
                    cloud=(math.sin(u*9+v*4)+math.sin(v*13-u*6)+math.cos(u*17-v*9))/6+.5
                    alpha=round(max(0,1-r*r)**1.5*(35+130*cloud)) if r<1 else 0
                else:
                    grid=min(abs((x+y*.55)%15-7.5),abs((x-y*.55)%15-7.5))<.7
                    alpha=(100 if grid else 24) if r<=1 else 0
                row.extend([210,243,246,max(0,min(255,alpha))])
            rows.append(bytes(row))
        data=b'\x89PNG\r\n\x1a\n'+chunk(b'IHDR',struct.pack('!2I5B',128,128,8,6,0,0,0))+chunk(b'IDAT',zlib.compress(b''.join(rows),9))+chunk(b'IEND',b'')
        (out/f'{name}.png').write_bytes(data)
    # Rear 3x3 blocks remain a solid mounting frame behind the cylindrical chamber.
    for block,texture in [('zero_point_energy_generator_controller','pedestal_metal'),('zero_point_generator_casing','pedestal_dark')]:
        (ASSETS/'models/block'/f'{block}.json').write_text(json.dumps({'parent':'minecraft:block/cube_all','textures':{'all':f'jsgzpm:block/ancient/{texture}'}},indent=2)+'\n')
    print(f'Generated {len(m.faces)} recharger mesh faces and two RGBA effect textures.')

if __name__=='__main__':build()
